---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grott

commonLabels:
  projectName: grott
  app: grott

resources:
  - namespace.yaml
  - service-account.yaml
  - grott-configmap.yaml
  - grott-deployment.yaml
  - grott-service.yaml
