---
apiVersion: kustomize.config.k8s.io/v1beta1

commonLabels:
  environment: production

resources:
  - ../base

patches:
  - target:
      kind: ConfigMap
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: production
